### ISSUE TITLE
Plantuml option causes exception

### ISSUE THREAD

**Issue by snow6oy** [tefra/xsdata-plantuml#7]
Hi, this looks like a very useful tool. I have a large number of WSDLs to analyse!

I am running xsdata on the command line after installing on macos using pip. Python version is 3.11. The default output is working fine. Adding -o plantuml option causes the exception. I fixed one error as follows 

```
/opt/homebrew/lib/python3.11/site-packages/xsdata_plantuml/generator.py

        resolver = DependenciesResolver(classes)
        #resolver = DependenciesResolver(packages=packages)

```
but then immediately ran into another - Ruff failed. Any clues on what causes that?

**Comment by tefra** [comment]
Thanks for reporting this @snow6oy, xsdata v24.1 introduced ruff formatting in the writer 💢

I am going to fix this, for now your best bet is to switch to `xsdata==23.8`

**Comment by tefra** [comment]
xsdata updated, I also released a new version of the plugin with misc project updates!
